### ISSUE TITLE
Getting NoneType Error

### ISSUE THREAD

**Issue by kasperhbo** [RichardoMrMu/python-onvif#1]
Dear,

I keep getting this error when trying to startup.

I have an HikVision DS-2CD55C5G0-IZS. 

self.requestc.Velocity.PanTilt.space = ptz_configuration_options.Spaces.ContinuousPanTiltVelocitySpace[0].URI
AttributeError: 'NoneType' object has no attribute 'PanTilt'

Can you maybe help solve this issue?

Thanks in advance!

**Comment by murfdogprod** [comment]
Did you find an answer to this? I have same issue

**Comment by kasperhbo** [comment]
It was because my camera didn't support panning and tilting. Thought it did
